easy_admin:
  site_name: 'MyPLE'
  design:
    brand_color: '#00134a'
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    menu:
      - { label: 'Scénario' }
      - { entity: 'Task', icon: 'cube', label: 'Tâches', default: true }
      - { entity: 'Activity', icon: 'cubes', label: 'Activités' }
      - { label: 'Outils' }
      - { entity: 'Tool', icon: 'th-list', label: 'Outils' }
      - { entity: 'ToolFamily', icon: 'th-list', label: "Familles" }
      - { entity: 'ToolTag', icon: 'th-list', label: "Tags" }
      - { label: 'Autre' }
      - { entity: 'Resource', icon: 'th-list', label: 'Ressources' }
      - { entity: 'News', icon: 'th-list', label: 'Actualités' }

fos_ck_editor:
  input_sync: true
  default_config: simple_config
  configs:
      simple_config:
          allowedContent: true
          toolbar:
            - { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', '-', 'CopyFormatting', 'RemoveFormat' ] }
            - { name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ] }
            - { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] }
            - { name: 'insert', items: [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar' ] }
            - { name: 'tools', items: [ 'Maximize' ] }