easy_admin:
  site_name: 'MyPLE'
  design:
    brand_color: '#00134a'
    menu:
      - { label: 'Scénario' }
      - { entity: 'Task', icon: 'cube', label: 'Tâches', default: true }
      - { entity: 'Activity', icon: 'cubes', label: 'Activités' }
      - { label: 'Outils' }
      - { entity: 'Tool', icon: 'th-list', label: 'Outils' }
      - { entity: 'ToolFamily', icon: 'th-list', label: "Familles" }
      - { entity: 'ToolTag', icon: 'th-list', label: "Tags" }
      - { label: 'Autre' }
      - { entity: 'Resource', icon: 'th-list', label: 'Ressources' }
      - { entity: 'News', icon: 'th-list', label: 'Actualités' }