easy_admin:
  entities:
    Activity:
      class: AppBundle\Entity\Activity
      list:
        sort: ['task', 'ASC']
        fields:
          - { property: 'nameFr', label: 'Nom' }
          - { property: 'task', label: 'Tâche' }
          - { property: 'rank', label: 'Position' }
          - { property: 'training', label: 'Exercice' }
      form:
        fields:
          - { type: 'tab', label: 'Général' }
          - { type: 'group', css_class: 'col-sm-12', label: 'Général' }
          - { property: 'humanUpdatedAt', label: 'Mise à jour' }
          - { property: 'task', label: 'Tâche', css_class: 'long' }
          - { property: 'rank', label: 'Position' }
          - { property: 'training', label: 'Exercice' }
          - { property: 'tools', label: 'Outils', css_class: 'long' }
          - { property: 'resources', label: 'Ressources', type: 'easyadmin_autocomplete', css_class: 'long' }
          - { type: 'tab', label: 'FR' }
          - { type: 'group', css_class: 'col-sm-12', label: 'Français' }
          - { property: 'nameFr', label: 'Nom', css_class: 'long' }
          - { property: 'goalFr', label: 'Finalités', type: 'fos_ckeditor' }
          - { property: 'stepsFr', label: 'Étapes', type: 'fos_ckeditor' }
          - { property: 'refFr', label: 'Référentiel', type: 'fos_ckeditor' }
          - { type: 'tab', label: 'DE' }
          - { type: 'group', css_class: 'col-sm-12', label: 'Allemand' }
          - { property: 'nameDe', label: 'Nom', css_class: 'long' }
          - { property: 'goalDe', label: 'Finalités', type: 'fos_ckeditor' }
          - { property: 'stepsDe', label: 'Étapes', type: 'fos_ckeditor' }
          - { property: 'refDe', label: 'Référentiel', type: 'fos_ckeditor' }
          - { type: 'tab', label: 'IT' }
          - { type: 'group', css_class: 'col-sm-12', label: 'Italien' }
          - { property: 'nameIt', label: 'Nom', css_class: 'long' }
          - { property: 'goalIt', label: 'Finalités', type: 'fos_ckeditor' }
          - { property: 'stepsIt', label: 'Étapes', type: 'fos_ckeditor' }
          - { property: 'refIt', label: 'Référentiel', type: 'fos_ckeditor' }