easy_admin:
  entities:
    Activity:
      class: AppBundle\Entity\Activity
      list:
        sort: ['nameFr', 'ASC']
        fields:
          - { property: 'nameFr', label: 'Nom' }
          - { property: 'task', label: 'Tâche' }
      form:
        fields:
          - { type: 'group', css_class: 'col-sm-9' }
          - { property: 'nameFr', label: 'Nom' }
          - { property: 'goalFr', label: 'Finalités', type: 'ckeditor' }
          - { property: 'stepsFr', label: 'Étapes', type: 'ckeditor' }
          - { property: 'refFr', label: 'Référentiel', type: 'ckeditor' }
          - { property: 'biblio', label: 'Bibliographies', type: 'ckeditor' }
          - { type: 'group', css_class: 'col-sm-3' }
          - { property: 'task', label: 'Tâche' }
          - { property: 'tools', label: 'Outils' }
          - { property: 'resources', label: 'Ressources', type: 'easyadmin_autocomplete' }