easy_admin:
  entities:
    FormationTag:
      class: AppBundle\Entity\FormationTag
      list:
        sort: ['nameFr', 'ASC']
        fields:
          - { property: 'nameFr', label: 'Nom' }
      form:
        fields:
          - { property: 'nameFr', label: 'Nom (FR)' }
          - { property: 'nameDe', label: 'Nom (DE)' }
          - { property: 'nameIt', label: 'Nom (IT)' }