easy_admin:
  entities:
    Resource:
      class: AppBundle\Entity\Resource
      list:
        sort: ['name', 'ASC']
        fields:
          - { property: 'imageName', label: 'Image', type: 'image', base_path: %app.path.resources% }
          - { property: 'name', label: 'Nom' }
          - { property: 'tutorial', label: 'Tutoriel' }
          - { property: 'type', label: 'Type' }
          - { property: 'date', label: 'Date' }
          - { property: 'author', label: 'Auteur' }
      form:
        fields:
          - { type: 'group', css_class: 'col-sm-9' }
          - { property: 'name', label: 'Nom' }
          - { property: 'url', label: 'Url' }
          - { property: 'additional', label: 'Informations additionnelles', type: 'ckeditor' }
          - { type: 'group', css_class: 'col-sm-3' }
          - { property: 'tutorial', label: 'Tutoriel' }
          - { property: 'type', label: 'Type' }
          - { property: 'date', label: 'Date' }
          - { property: 'author', label: 'Auteur' }
          - { property: 'langs', label: 'Langues' }
          - { property: 'imageFile', label: 'Image', type: 'vich_image' }
          - { property: 'tools', label: 'Outils' }