easy_admin:
  entities:
    Tool:
      class: AppBundle\Entity\Tool
      list:
        sort: ['name', 'ASC']
        fields:
          - { property: 'imageName', label: 'Image', type: 'image', base_path: 'uploads' }
          - { property: 'name', label: 'Nom' }
          - { property: 'families', label: "Familles d'outils" }
      form:
        fields:
          - { type: 'group', css_class: 'col-sm-9' }
          - { property: 'name', label: 'Nom' }
          - { property: 'link', label: 'Lien' }
          - { property: 'infoFr', label: 'Info (FR)', type: 'fos_ckeditor' }
          - { property: 'infoDe', label: 'Info (DE)', type: 'fos_ckeditor' }
          - { property: 'infoIt', label: 'Info (IT)', type: 'fos_ckeditor' }
          - { type: 'group', css_class: 'col-sm-3' }
          - { property: 'families', label: "Familles d'outils" }
          - { property: 'tags', label: "Tags" }
          - { property: 'imageFile', label: 'Image', type: 'vich_image' }