<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{
  public function countAll()
  {
    return $this->createQueryBuilder('formation')
      ->select('COUNT(formation)')
      ->getQuery()->getSingleScalarResult();
  }
}
