<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ToolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolRepository extends EntityRepository
{
  public function countAll()
  {
    return $this->createQueryBuilder('tool')
      ->select('COUNT(tool)')
      ->getQuery()->getSingleScalarResult();
  }
}
