<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ToolFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolFamilyRepository extends EntityRepository
{
  public function findAll()
  {
    return $this->findBy(array(), array('nameFr' => 'ASC'));
  }
  
  public function countAll()
  {
    return $this->createQueryBuilder('tool')
      ->select('COUNT(tool)')
      ->getQuery()->getSingleScalarResult();
  }
}
