imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.tool_images: /uploads/images/tools
    app.path.toolFamily_comparatives: /uploads/files/toolFamilies

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true
    translator: { fallbacks: [ '%locale%'] }

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# assetic
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

# vich uploader
vich_uploader:
    db_driver: orm
    mappings:
        toolFamily_comparative:
            uri_prefix:         %app.path.toolFamily_comparatives%
            upload_destination: '%kernel.root_dir%/../web/uploads/files/toolFamilies'
            namer:               vich_uploader.namer_uniqid
        tool_image:
            uri_prefix:         %app.path.tool_images%
            upload_destination: '%kernel.root_dir%/../web/uploads/images/tools'
            namer:              vich_uploader.namer_uniqid

# ivory ckeditor
ivory_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar:
                - { name: 'styles', items: ['Bold', 'Italic', 'BulletedList', 'Link'] }
                - { name: 'paragraph', items : ['NumberedList','BulletedList', 'Blockquote','-','Outdent','Indent','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-'] }
                - { name: 'insert', items : ['Image'] }

# easy admin
easy_admin:
    site_name: 'MyPLE'
    design:
        brand_color: '#00134a'
    entities:
        ToolFamily:
            class: AppBundle\Entity\ToolFamily
            list:
                sort: ['nameFr', 'ASC']
                fields:
                    - { property: 'nameFr', label: 'Nom' }
            form:
                fields:
                    - { property: 'nameFr', label: 'Nom' }
                    - { property: 'helpFr', label: 'Aide' }
                    - { property: 'comparativeFileFr', label: 'Tableau comparatif', type: 'vich_file' }
        Tool:
            class: AppBundle\Entity\Tool
            list:
                sort: ['name', 'ASC']
                fields:
                    - { property: 'imageName', label: 'Image', type: 'image', base_path: %app.path.tool_images% }
                    - { property: 'name', label: 'Nom' }
                    - { property: 'toolFamily', label: "Famille d'outils" }
            form:
                fields:
                    - { property: 'toolFamily', label: "Famille d'outils" }
                    - { property: 'name', label: 'Nom' }
                    - { property: 'link', label: 'Lien' }
                    - { property: 'infoFr', label: 'Info'}
                    - { property: 'imageFile', label: 'Image', type: 'vich_image' }
        Task:
            class: AppBundle\Entity\Task
            list:
                sort: ['nameFr', 'ASC']
                fields:
                    - { property: 'nameFr', label: 'Nom' }
            form:
                fields:
                    - { property: 'nameFr', label: 'Nom' }
        Activity:
            class: AppBundle\Entity\Activity
            list:
                sort: ['nameFr', 'ASC']
                fields:
                    - { property: 'nameFr', label: 'Nom' }
                    - { property: 'task', label: 'Tâche' }
            form:
                fields:
                    - { property: 'task', label: 'Tâche' }
                    - { property: 'nameFr', label: 'Nom' }
                    - { property: 'helpFr', label: 'Aide', type: 'ckeditor' }
                    - { property: 'stepsFr', label: 'Étapes', type: 'ckeditor' }
                    - { property: 'goalFr', label: 'Finalités', type: 'ckeditor' }
                    - { property: 'refFr', label: 'Référentiel', type: 'ckeditor' }
                    - { property: 'biblio', label: 'Bibliographies', type: 'ckeditor' }