liip_imagine:
  loaders:
    default:
      filesystem:
        locator: filesystem_insecure
  resolvers:
    default:
      web_path: ~
  filter_sets:
    cache: ~
    thumb_200:
      quality: 100
      filters:
        thumbnail: { size: [200, 200], mode: outbound }