liip_imagine:
  loaders:
    default:
      filesystem:
        locator: filesystem_insecure
  resolvers:
    default:
      web_path:
        web_root: '%kernel.project_dir%/web'
        cache_prefix: ~
  filter_sets:
    cache: ~
    thumb_50:
      quality: 100
      filters:
        thumbnail: { size: [50, 50], mode: outbound }