liip_imagine:
  loaders:
    default:
      filesystem:
        data_root: '%kernel.root_dir%/../../../shared/web/'
  resolvers:
    default:
      web_path:
        web_root: '%kernel.root_dir%/../../../shared/web/'
        cache_prefix: media/cache
  filter_sets:
    cache: ~
    thumb_50:
      quality: 100
      filters:
        thumbnail: { size: [50, 50], mode: outbound }